# Generated by Django 5.1.4 on 2024-12-25 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('artist', models.CharField(max_length=100)),
                ('album', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=100)),
                ('release_year', models.DateField()),
                ('cover_image', models.ImageField(upload_to='track_images/')),
                ('audio_file', models.FileField(upload_to='track_files/')),
            ],
        ),
    ]
