# Generated by Django 5.1.4 on 2024-12-26 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='track',
            old_name='release_year',
            new_name='release_date',
        ),
    ]
